version: "3.9"

services:

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/env/.env
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    networks:
      - connected

  backend-1:
    build: ./backend
    env_file:
      - ./backend/env/.env
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]
    networks:
      - connected

  backend-2:
    build: ./backend
    env_file:
      - ./backend/env/.env
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]
    networks:
      - connected

  backend-3:
    build: ./backend
    env_file:
      - ./backend/env/.env
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]
    networks:
      - connected

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./backend/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-1
      - backend-2
      - backend-3
    networks:
      - connected

networks:
  connected:
    driver: bridge
