version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/env/.env
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    networks:
      - connected

  backend:
    build: ./backend
    env_file:
      - ./backend/env/.env
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]
    networks:
      - connected

networks:
  connected:
    driver: bridge
